// Code generated by goctl. DO NOT EDIT.
// Source: asr.proto

package server

import (
	"context"

	"go/go/internal/logic"
	"go/go/internal/svc"
	"go/go/pb/asr"
)

type ASRServer struct {
	svcCtx *svc.ServiceContext
	asr.UnimplementedASRServer
}

func NewASRServer(svcCtx *svc.ServiceContext) *ASRServer {
	return &ASRServer{
		svcCtx: svcCtx,
	}
}

func (s *ASRServer) ASR(ctx context.Context, in *asr.AsrRequest) (*asr.AsrResponse, error) {
	l := logic.NewASRLogic(ctx, s.svcCtx)
	return l.ASR(in)
}
