// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.1
// source: go/asr.proto

package asr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AsrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename   string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Audiobytes []byte `protobuf:"bytes,2,opt,name=audiobytes,proto3" json:"audiobytes,omitempty"`
}

func (x *AsrRequest) Reset() {
	*x = AsrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_asr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsrRequest) ProtoMessage() {}

func (x *AsrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_asr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsrRequest.ProtoReflect.Descriptor instead.
func (*AsrRequest) Descriptor() ([]byte, []int) {
	return file_go_asr_proto_rawDescGZIP(), []int{0}
}

func (x *AsrRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AsrRequest) GetAudiobytes() []byte {
	if x != nil {
		return x.Audiobytes
	}
	return nil
}

type AsrResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Audiotext string `protobuf:"bytes,1,opt,name=audiotext,proto3" json:"audiotext,omitempty"`
}

func (x *AsrResponse) Reset() {
	*x = AsrResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_asr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsrResponse) ProtoMessage() {}

func (x *AsrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_asr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsrResponse.ProtoReflect.Descriptor instead.
func (*AsrResponse) Descriptor() ([]byte, []int) {
	return file_go_asr_proto_rawDescGZIP(), []int{1}
}

func (x *AsrResponse) GetAudiotext() string {
	if x != nil {
		return x.Audiotext
	}
	return ""
}

var File_go_asr_proto protoreflect.FileDescriptor

var file_go_asr_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x6f, 0x2f, 0x61, 0x73, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48,
	0x0a, 0x0a, 0x41, 0x73, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69,
	0x6f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x61, 0x75,
	0x64, 0x69, 0x6f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x22, 0x2b, 0x0a, 0x0b, 0x41, 0x73, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x64, 0x69,
	0x6f, 0x74, 0x65, 0x78, 0x74, 0x32, 0x29, 0x0a, 0x03, 0x41, 0x53, 0x52, 0x12, 0x22, 0x0a, 0x03,
	0x41, 0x53, 0x52, 0x12, 0x0b, 0x2e, 0x41, 0x73, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0c, 0x2e, 0x41, 0x73, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61, 0x73, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_go_asr_proto_rawDescOnce sync.Once
	file_go_asr_proto_rawDescData = file_go_asr_proto_rawDesc
)

func file_go_asr_proto_rawDescGZIP() []byte {
	file_go_asr_proto_rawDescOnce.Do(func() {
		file_go_asr_proto_rawDescData = protoimpl.X.CompressGZIP(file_go_asr_proto_rawDescData)
	})
	return file_go_asr_proto_rawDescData
}

var file_go_asr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_go_asr_proto_goTypes = []interface{}{
	(*AsrRequest)(nil),  // 0: AsrRequest
	(*AsrResponse)(nil), // 1: AsrResponse
}
var file_go_asr_proto_depIdxs = []int32{
	0, // 0: ASR.ASR:input_type -> AsrRequest
	1, // 1: ASR.ASR:output_type -> AsrResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_go_asr_proto_init() }
func file_go_asr_proto_init() {
	if File_go_asr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_go_asr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_asr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsrResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_go_asr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_asr_proto_goTypes,
		DependencyIndexes: file_go_asr_proto_depIdxs,
		MessageInfos:      file_go_asr_proto_msgTypes,
	}.Build()
	File_go_asr_proto = out.File
	file_go_asr_proto_rawDesc = nil
	file_go_asr_proto_goTypes = nil
	file_go_asr_proto_depIdxs = nil
}
