# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tasr.proto\"2\n\nAsrRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x12\n\naudiobytes\x18\x02 \x01(\x0c\" \n\x0b\x41srResponse\x12\x11\n\taudiotext\x18\x01 \x01(\t2)\n\x03\x41SR\x12\"\n\x03\x41SR\x12\x0b.AsrRequest\x1a\x0c.AsrResponse\"\x00\x62\x06proto3')



_ASRREQUEST = DESCRIPTOR.message_types_by_name['AsrRequest']
_ASRRESPONSE = DESCRIPTOR.message_types_by_name['AsrResponse']
AsrRequest = _reflection.GeneratedProtocolMessageType('AsrRequest', (_message.Message,), {
  'DESCRIPTOR' : _ASRREQUEST,
  '__module__' : 'asr_pb2'
  # @@protoc_insertion_point(class_scope:AsrRequest)
  })
_sym_db.RegisterMessage(AsrRequest)

AsrResponse = _reflection.GeneratedProtocolMessageType('AsrResponse', (_message.Message,), {
  'DESCRIPTOR' : _ASRRESPONSE,
  '__module__' : 'asr_pb2'
  # @@protoc_insertion_point(class_scope:AsrResponse)
  })
_sym_db.RegisterMessage(AsrResponse)

_ASR = DESCRIPTOR.services_by_name['ASR']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ASRREQUEST._serialized_start=13
  _ASRREQUEST._serialized_end=63
  _ASRRESPONSE._serialized_start=65
  _ASRRESPONSE._serialized_end=97
  _ASR._serialized_start=99
  _ASR._serialized_end=140
# @@protoc_insertion_point(module_scope)
