# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pb.asr_pb2 as asr__pb2


class ASRStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ASR = channel.unary_unary(
                '/ASR/ASR',
                request_serializer=asr__pb2.AsrRequest.SerializeToString,
                response_deserializer=asr__pb2.AsrResponse.FromString,
                )


class ASRServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ASR(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ASRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ASR': grpc.unary_unary_rpc_method_handler(
                    servicer.ASR,
                    request_deserializer=asr__pb2.AsrRequest.FromString,
                    response_serializer=asr__pb2.AsrResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ASR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ASR(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ASR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ASR/ASR',
            asr__pb2.AsrRequest.SerializeToString,
            asr__pb2.AsrResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
